# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.srcs/sources_1/bd/ila/ip/ila_ila_0_0/ila_ila_0_0.xci
# IP: The module: 'ila_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.gen/sources_1/bd/ila/ip/ila_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.gen/sources_1/bd/ila/ip/ila_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.gen/sources_1/bd/ila/ip/ila_ila_0_0/ila_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.srcs/sources_1/bd/ila/ip/ila_ila_0_0/ila_ila_0_0.xci
# IP: The module: 'ila_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.gen/sources_1/bd/ila/ip/ila_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.gen/sources_1/bd/ila/ip/ila_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.gen/sources_1/bd/ila/ip/ila_ila_0_0/ila_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
