# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.runs/synth_1/CPU_DSP.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.cache/wt [current_project]
set_property parent.project_path C:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:cmod_a7-35t:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog C:/Users/leand/Desktop/RISC_V_UNISA/ID/RISCV.sv
set_property file_type "Verilog Header" [get_files C:/Users/leand/Desktop/RISC_V_UNISA/ID/RISCV.sv]
read_mem C:/Users/leand/Desktop/RISC_V_UNISA/IF/mem.mem
read_verilog -library xil_defaultlib -sv {
  C:/Users/leand/Desktop/RISC_V_UNISA/EX/ALU.sv
  C:/Users/leand/Desktop/RISC_V_UNISA/DSP/DSP.sv
  C:/Users/leand/Desktop/RISC_V_UNISA/CPU_DSP/MEM_DSP.sv
  C:/Users/leand/Desktop/RISC_V_UNISA/CPU_DSP.sv
}
read_verilog -library xil_defaultlib {
  C:/Users/leand/Desktop/RISC_V_UNISA/EX/ADD.v
  C:/Users/leand/Desktop/RISC_V_UNISA/IF/ADD4.v
  C:/Users/leand/Desktop/RISC_V_UNISA/ID/ALU_CONTROL.v
  C:/Users/leand/Desktop/RISC_V_UNISA/MEM/BRANCH.v
  C:/Users/leand/Desktop/RISC_V_UNISA/ID/CONTROL.v
  C:/Users/leand/Desktop/RISC_V_UNISA/CPU_pipeline.v
  C:/Users/leand/Desktop/RISC_V_UNISA/EX/EX.v
  C:/Users/leand/Desktop/RISC_V_UNISA/ID/GENERADOR_CONSTANTE.v
  C:/Users/leand/Desktop/RISC_V_UNISA/ID/ID.v
  C:/Users/leand/Desktop/RISC_V_UNISA/IF/IF.v
  C:/Users/leand/Desktop/RISC_V_UNISA/MEM/MEM.v
  C:/Users/leand/Desktop/RISC_V_UNISA/MEM/MEM_DATA.v
  C:/Users/leand/Desktop/RISC_V_UNISA/IF/MEM_INST.v
  C:/Users/leand/Desktop/RISC_V_UNISA/DSP/MULT.v
  C:/Users/leand/Desktop/RISC_V_UNISA/COMMON/MUX32.v
  C:/Users/leand/Desktop/RISC_V_UNISA/IF/PC.v
  C:/Users/leand/Desktop/RISC_V_UNISA/ID/REGISTERS.v
  C:/Users/leand/Desktop/RISC_V_UNISA/DSP/SUB.v
  C:/Users/leand/Desktop/RISC_V_UNISA/DSP/SUM.v
}
add_files C:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.srcs/sources_1/bd/vio/vio.bd
set_property used_in_implementation false [get_files -all c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.gen/sources_1/bd/vio/ip/vio_vio_0_0_1/vio_vio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.gen/sources_1/bd/vio/ip/vio_vio_0_0_1/vio_vio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.gen/sources_1/bd/vio/vio_ooc.xdc]

add_files C:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.srcs/sources_1/bd/ila/ila.bd
set_property used_in_synthesis false [get_files -all c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.gen/sources_1/bd/ila/ip/ila_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.gen/sources_1/bd/ila/ip/ila_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.gen/sources_1/bd/ila/ip/ila_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.gen/sources_1/bd/ila/ip/ila_ila_0_0/ila_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.gen/sources_1/bd/ila/ila_ooc.xdc]

add_files C:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.srcs/sources_1/bd/clk_mmcm/clk_mmcm.bd
set_property used_in_implementation false [get_files -all c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.gen/sources_1/bd/clk_mmcm/ip/clk_mmcm_clk_wiz_0_0_3/clk_mmcm_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.gen/sources_1/bd/clk_mmcm/ip/clk_mmcm_clk_wiz_0_0_3/clk_mmcm_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.gen/sources_1/bd/clk_mmcm/ip/clk_mmcm_clk_wiz_0_0_3/clk_mmcm_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.gen/sources_1/bd/clk_mmcm/clk_mmcm_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/leand/Desktop/RISC_V_UNISA/Arty-A7-35-Master.xdc
set_property used_in_implementation false [get_files C:/Users/leand/Desktop/RISC_V_UNISA/Arty-A7-35-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.srcs/utils_1/imports/synth_1/CPU_DSP.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top CPU_DSP -part xc7a35tcpg236-1 -global_retiming on
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CPU_DSP.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file CPU_DSP_utilization_synth.rpt -pb CPU_DSP_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
