# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/leand/Desktop/RISC_V_UNISA/Arty-A7-35-Master.xdc

# Block Designs: bd/vio/vio.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vio || ORIG_REF_NAME==vio} -quiet] -quiet

# IP: bd/vio/ip/vio_vio_0_0/vio_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vio_vio_0_0 || ORIG_REF_NAME==vio_vio_0_0} -quiet] -quiet

# Block Designs: bd/ila/ila.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila || ORIG_REF_NAME==ila} -quiet] -quiet

# IP: bd/ila/ip/ila_ila_0_0/ila_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_ila_0_0 || ORIG_REF_NAME==ila_ila_0_0} -quiet] -quiet

# Block Designs: bd/clk_mmcm/clk_mmcm.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_mmcm || ORIG_REF_NAME==clk_mmcm} -quiet] -quiet

# IP: bd/clk_mmcm/ip/clk_mmcm_clk_wiz_0_0/clk_mmcm_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_mmcm_clk_wiz_0_0 || ORIG_REF_NAME==clk_mmcm_clk_wiz_0_0} -quiet] -quiet

# XDC: c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.gen/sources_1/bd/vio/vio_ooc.xdc

# XDC: c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.gen/sources_1/bd/ila/ila_ooc.xdc

# XDC: c:/Users/leand/Desktop/RISC_V_UNISA/RISC_V_CPU_DSP/RISC_V_CPU_DSP.gen/sources_1/bd/clk_mmcm/clk_mmcm_ooc.xdc
